// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: noble/dollar/vaults/v2/nav.proto

package v2

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// AUMBand defines the pricing bands for deposits and withdrawals
type AUMBand struct {
	// Lower bound of the band (basis points above/below AUM)
	LowerBound int32 `protobuf:"varint,1,opt,name=lower_bound,json=lowerBound,proto3" json:"lower_bound,omitempty"`
	// Upper bound of the band (basis points above/below AUM)
	UpperBound int32 `protobuf:"varint,2,opt,name=upper_bound,json=upperBound,proto3" json:"upper_bound,omitempty"`
}

func (m *AUMBand) Reset()         { *m = AUMBand{} }
func (m *AUMBand) String() string { return proto.CompactTextString(m) }
func (*AUMBand) ProtoMessage()    {}
func (*AUMBand) Descriptor() ([]byte, []int) {
	return fileDescriptor_893b9e92a5bdeb81, []int{0}
}
func (m *AUMBand) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AUMBand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AUMBand.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AUMBand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AUMBand.Merge(m, src)
}
func (m *AUMBand) XXX_Size() int {
	return m.Size()
}
func (m *AUMBand) XXX_DiscardUnknown() {
	xxx_messageInfo_AUMBand.DiscardUnknown(m)
}

var xxx_messageInfo_AUMBand proto.InternalMessageInfo

func (m *AUMBand) GetLowerBound() int32 {
	if m != nil {
		return m.LowerBound
	}
	return 0
}

func (m *AUMBand) GetUpperBound() int32 {
	if m != nil {
		return m.UpperBound
	}
	return 0
}

// AUMConfig defines the configuration for AUM-based pricing
type AUMConfig struct {
	// Base AUM bands for deposits
	DepositBands []*AUMBand `protobuf:"bytes,1,rep,name=deposit_bands,json=depositBands,proto3" json:"deposit_bands,omitempty"`
	// Base AUM bands for withdrawals
	WithdrawalBands []*AUMBand `protobuf:"bytes,2,rep,name=withdrawal_bands,json=withdrawalBands,proto3" json:"withdrawal_bands,omitempty"`
	// Minimum AUM update interval (seconds)
	MinAumUpdateInterval int64 `protobuf:"varint,3,opt,name=min_aum_update_interval,json=minAumUpdateInterval,proto3" json:"min_aum_update_interval,omitempty"`
	// Maximum allowed AUM deviation before emergency controls (basis points)
	MaxAumDeviation int32 `protobuf:"varint,4,opt,name=max_aum_deviation,json=maxAumDeviation,proto3" json:"max_aum_deviation,omitempty"`
	// Emergency circuit breaker threshold (basis points)
	CircuitBreakerThreshold int32 `protobuf:"varint,5,opt,name=circuit_breaker_threshold,json=circuitBreakerThreshold,proto3" json:"circuit_breaker_threshold,omitempty"`
}

func (m *AUMConfig) Reset()         { *m = AUMConfig{} }
func (m *AUMConfig) String() string { return proto.CompactTextString(m) }
func (*AUMConfig) ProtoMessage()    {}
func (*AUMConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_893b9e92a5bdeb81, []int{1}
}
func (m *AUMConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AUMConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AUMConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AUMConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AUMConfig.Merge(m, src)
}
func (m *AUMConfig) XXX_Size() int {
	return m.Size()
}
func (m *AUMConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AUMConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AUMConfig proto.InternalMessageInfo

func (m *AUMConfig) GetDepositBands() []*AUMBand {
	if m != nil {
		return m.DepositBands
	}
	return nil
}

func (m *AUMConfig) GetWithdrawalBands() []*AUMBand {
	if m != nil {
		return m.WithdrawalBands
	}
	return nil
}

func (m *AUMConfig) GetMinAumUpdateInterval() int64 {
	if m != nil {
		return m.MinAumUpdateInterval
	}
	return 0
}

func (m *AUMConfig) GetMaxAumDeviation() int32 {
	if m != nil {
		return m.MaxAumDeviation
	}
	return 0
}

func (m *AUMConfig) GetCircuitBreakerThreshold() int32 {
	if m != nil {
		return m.CircuitBreakerThreshold
	}
	return 0
}

// AUMInfo represents current AUM information for a vault
type AUMInfo struct {
	// Current AUM value
	CurrentAum cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=current_aum,json=currentAum,proto3,customtype=cosmossdk.io/math.Int" json:"current_aum"`
	// Previous AUM value
	PreviousAum cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=previous_aum,json=previousAum,proto3,customtype=cosmossdk.io/math.Int" json:"previous_aum"`
	// Last update timestamp
	LastUpdate time.Time `protobuf:"bytes,3,opt,name=last_update,json=lastUpdate,proto3,stdtime" json:"last_update"`
}

func (m *AUMInfo) Reset()         { *m = AUMInfo{} }
func (m *AUMInfo) String() string { return proto.CompactTextString(m) }
func (*AUMInfo) ProtoMessage()    {}
func (*AUMInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_893b9e92a5bdeb81, []int{2}
}
func (m *AUMInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AUMInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AUMInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AUMInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AUMInfo.Merge(m, src)
}
func (m *AUMInfo) XXX_Size() int {
	return m.Size()
}
func (m *AUMInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AUMInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AUMInfo proto.InternalMessageInfo

func (m *AUMInfo) GetLastUpdate() time.Time {
	if m != nil {
		return m.LastUpdate
	}
	return time.Time{}
}

// CircuitBreakerTrip records when a circuit breaker was triggered
type CircuitBreakerTrip struct {
	// AUM change that triggered the circuit breaker (basis points)
	ChangeBps int32 `protobuf:"varint,1,opt,name=change_bps,json=changeBps,proto3" json:"change_bps,omitempty"`
	// Remote position ID that caused the circuit breaker to trigger
	RemotePositionId uint64 `protobuf:"varint,2,opt,name=remote_position_id,json=remotePositionId,proto3" json:"remote_position_id,omitempty"`
	// Timestamp when circuit breaker was triggered
	TriggeredAt time.Time `protobuf:"bytes,3,opt,name=triggered_at,json=triggeredAt,proto3,stdtime" json:"triggered_at"`
	// Previous AUM before the change
	PreviousAum cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=previous_aum,json=previousAum,proto3,customtype=cosmossdk.io/math.Int" json:"previous_aum"`
	// Attempted new AUM that triggered the breaker
	AttemptedAum cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=attempted_aum,json=attemptedAum,proto3,customtype=cosmossdk.io/math.Int" json:"attempted_aum"`
}

func (m *CircuitBreakerTrip) Reset()         { *m = CircuitBreakerTrip{} }
func (m *CircuitBreakerTrip) String() string { return proto.CompactTextString(m) }
func (*CircuitBreakerTrip) ProtoMessage()    {}
func (*CircuitBreakerTrip) Descriptor() ([]byte, []int) {
	return fileDescriptor_893b9e92a5bdeb81, []int{3}
}
func (m *CircuitBreakerTrip) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CircuitBreakerTrip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CircuitBreakerTrip.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CircuitBreakerTrip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CircuitBreakerTrip.Merge(m, src)
}
func (m *CircuitBreakerTrip) XXX_Size() int {
	return m.Size()
}
func (m *CircuitBreakerTrip) XXX_DiscardUnknown() {
	xxx_messageInfo_CircuitBreakerTrip.DiscardUnknown(m)
}

var xxx_messageInfo_CircuitBreakerTrip proto.InternalMessageInfo

func (m *CircuitBreakerTrip) GetChangeBps() int32 {
	if m != nil {
		return m.ChangeBps
	}
	return 0
}

func (m *CircuitBreakerTrip) GetRemotePositionId() uint64 {
	if m != nil {
		return m.RemotePositionId
	}
	return 0
}

func (m *CircuitBreakerTrip) GetTriggeredAt() time.Time {
	if m != nil {
		return m.TriggeredAt
	}
	return time.Time{}
}

// AUMUpdate represents a AUM update event
type AUMUpdate struct {
	// New AUM point
	NewAum cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=new_aum,json=newAum,proto3,customtype=cosmossdk.io/math.Int" json:"new_aum"`
	// Update timestamp
	Timestamp time.Time `protobuf:"bytes,2,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
	// Block height
	BlockHeight int64 `protobuf:"varint,3,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
}

func (m *AUMUpdate) Reset()         { *m = AUMUpdate{} }
func (m *AUMUpdate) String() string { return proto.CompactTextString(m) }
func (*AUMUpdate) ProtoMessage()    {}
func (*AUMUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_893b9e92a5bdeb81, []int{4}
}
func (m *AUMUpdate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AUMUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AUMUpdate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AUMUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AUMUpdate.Merge(m, src)
}
func (m *AUMUpdate) XXX_Size() int {
	return m.Size()
}
func (m *AUMUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_AUMUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_AUMUpdate proto.InternalMessageInfo

func (m *AUMUpdate) GetTimestamp() time.Time {
	if m != nil {
		return m.Timestamp
	}
	return time.Time{}
}

func (m *AUMUpdate) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

// PricingInfo provides pricing information for deposits/withdrawals
type PricingInfo struct {
	// Current yield rate (APY)
	YieldRate cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=yield_rate,json=yieldRate,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"yield_rate"`
	// Applied AUM band
	AppliedBand *AUMBand `protobuf:"bytes,2,opt,name=applied_band,json=appliedBand,proto3" json:"applied_band,omitempty"`
	// Effective fee rate
	EffectiveFeeRate int32 `protobuf:"varint,3,opt,name=effective_fee_rate,json=effectiveFeeRate,proto3" json:"effective_fee_rate,omitempty"`
}

func (m *PricingInfo) Reset()         { *m = PricingInfo{} }
func (m *PricingInfo) String() string { return proto.CompactTextString(m) }
func (*PricingInfo) ProtoMessage()    {}
func (*PricingInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_893b9e92a5bdeb81, []int{5}
}
func (m *PricingInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PricingInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PricingInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PricingInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PricingInfo.Merge(m, src)
}
func (m *PricingInfo) XXX_Size() int {
	return m.Size()
}
func (m *PricingInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PricingInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PricingInfo proto.InternalMessageInfo

func (m *PricingInfo) GetAppliedBand() *AUMBand {
	if m != nil {
		return m.AppliedBand
	}
	return nil
}

func (m *PricingInfo) GetEffectiveFeeRate() int32 {
	if m != nil {
		return m.EffectiveFeeRate
	}
	return 0
}

// LossEvent represents a loss in vault value
type LossEvent struct {
	// Amount of loss
	LossAmount cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=loss_amount,json=lossAmount,proto3,customtype=cosmossdk.io/math.Int" json:"loss_amount"`
	// Previous AUM before loss
	PreviousAum cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=previous_aum,json=previousAum,proto3,customtype=cosmossdk.io/math.Int" json:"previous_aum"`
	// New AUM after loss
	NewAum cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=new_aum,json=newAum,proto3,customtype=cosmossdk.io/math.Int" json:"new_aum"`
	// Timestamp of loss
	Timestamp time.Time `protobuf:"bytes,4,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
}

func (m *LossEvent) Reset()         { *m = LossEvent{} }
func (m *LossEvent) String() string { return proto.CompactTextString(m) }
func (*LossEvent) ProtoMessage()    {}
func (*LossEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_893b9e92a5bdeb81, []int{6}
}
func (m *LossEvent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LossEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LossEvent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LossEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LossEvent.Merge(m, src)
}
func (m *LossEvent) XXX_Size() int {
	return m.Size()
}
func (m *LossEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_LossEvent.DiscardUnknown(m)
}

var xxx_messageInfo_LossEvent proto.InternalMessageInfo

func (m *LossEvent) GetTimestamp() time.Time {
	if m != nil {
		return m.Timestamp
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*AUMBand)(nil), "noble.dollar.vaults.v2.AUMBand")
	proto.RegisterType((*AUMConfig)(nil), "noble.dollar.vaults.v2.AUMConfig")
	proto.RegisterType((*AUMInfo)(nil), "noble.dollar.vaults.v2.AUMInfo")
	proto.RegisterType((*CircuitBreakerTrip)(nil), "noble.dollar.vaults.v2.CircuitBreakerTrip")
	proto.RegisterType((*AUMUpdate)(nil), "noble.dollar.vaults.v2.AUMUpdate")
	proto.RegisterType((*PricingInfo)(nil), "noble.dollar.vaults.v2.PricingInfo")
	proto.RegisterType((*LossEvent)(nil), "noble.dollar.vaults.v2.LossEvent")
}

func init() { proto.RegisterFile("noble/dollar/vaults/v2/nav.proto", fileDescriptor_893b9e92a5bdeb81) }

var fileDescriptor_893b9e92a5bdeb81 = []byte{
	// 836 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xbf, 0x8f, 0x1b, 0x45,
	0x14, 0xbe, 0xb5, 0x2f, 0x09, 0x9e, 0x75, 0x94, 0xcb, 0x28, 0x10, 0xe7, 0x10, 0xf6, 0x61, 0x9a,
	0x53, 0x14, 0x76, 0xd1, 0x45, 0x50, 0x20, 0x51, 0x78, 0x73, 0x01, 0x0c, 0x89, 0x14, 0x4c, 0xdc,
	0xd0, 0xac, 0xc6, 0xbb, 0xcf, 0xeb, 0xd1, 0xed, 0xcc, 0xac, 0x66, 0x66, 0xd7, 0x77, 0xfc, 0x15,
	0xf9, 0x33, 0x28, 0x29, 0x28, 0xa1, 0xa1, 0x4a, 0x19, 0x51, 0x44, 0x88, 0x22, 0xa0, 0xbb, 0x82,
	0x7f, 0x81, 0x12, 0xcd, 0x0f, 0xfb, 0x82, 0x82, 0x44, 0x30, 0xa1, 0xb1, 0x3c, 0xef, 0x7d, 0xef,
	0x9b, 0x79, 0xdf, 0x7c, 0x6f, 0x16, 0xed, 0x71, 0x31, 0x2b, 0x21, 0xce, 0x45, 0x59, 0x12, 0x19,
	0x37, 0xa4, 0x2e, 0xb5, 0x8a, 0x9b, 0x83, 0x98, 0x93, 0x26, 0xaa, 0xa4, 0xd0, 0x02, 0xbf, 0x61,
	0x11, 0x91, 0x43, 0x44, 0x0e, 0x11, 0x35, 0x07, 0xbb, 0x57, 0x09, 0xa3, 0x5c, 0xc4, 0xf6, 0xd7,
	0x41, 0x77, 0x6f, 0x64, 0x42, 0x31, 0xa1, 0x52, 0xbb, 0x8a, 0xdd, 0xc2, 0xa7, 0xae, 0x15, 0xa2,
	0x10, 0x2e, 0x6e, 0xfe, 0xf9, 0xe8, 0xa0, 0x10, 0xa2, 0x28, 0x21, 0xb6, 0xab, 0x59, 0x3d, 0x8f,
	0x35, 0x65, 0xa0, 0x34, 0x61, 0x95, 0x03, 0x0c, 0x3f, 0x47, 0x97, 0x46, 0xd3, 0xfb, 0x09, 0xe1,
	0x39, 0x1e, 0xa0, 0xb0, 0x14, 0x4b, 0x90, 0xe9, 0x4c, 0xd4, 0x3c, 0xef, 0x05, 0x7b, 0xc1, 0xfe,
	0x85, 0x09, 0xb2, 0xa1, 0xc4, 0x44, 0x0c, 0xa0, 0xae, 0xaa, 0x35, 0xa0, 0xe5, 0x00, 0x36, 0x64,
	0x01, 0xc3, 0xef, 0x5b, 0xa8, 0x33, 0x9a, 0xde, 0xbf, 0x23, 0xf8, 0x9c, 0x16, 0xf8, 0x10, 0x5d,
	0xce, 0xa1, 0x12, 0x8a, 0xea, 0x74, 0x46, 0x78, 0xae, 0x7a, 0xc1, 0x5e, 0x7b, 0x3f, 0x3c, 0x18,
	0x44, 0x7f, 0xdf, 0x6f, 0xe4, 0xcf, 0x31, 0xe9, 0xfa, 0x2a, 0xb3, 0x50, 0xf8, 0x33, 0xb4, 0xb3,
	0xa4, 0x7a, 0x91, 0x4b, 0xb2, 0x24, 0xa5, 0x27, 0x6a, 0xbd, 0x1c, 0xd1, 0x95, 0xf3, 0x42, 0xc7,
	0xf5, 0x3e, 0xba, 0xce, 0x28, 0x4f, 0x49, 0xcd, 0xd2, 0xba, 0xca, 0x89, 0x86, 0x94, 0x72, 0x0d,
	0xb2, 0x21, 0x65, 0xaf, 0xbd, 0x17, 0xec, 0xb7, 0x27, 0xd7, 0x18, 0xe5, 0xa3, 0x9a, 0x4d, 0x6d,
	0x72, 0xec, 0x73, 0xf8, 0x26, 0xba, 0xca, 0xc8, 0xb1, 0x2d, 0xcb, 0xa1, 0xa1, 0x44, 0x53, 0xc1,
	0x7b, 0xdb, 0xb6, 0xfb, 0x2b, 0x8c, 0x1c, 0x8f, 0x6a, 0x76, 0xb8, 0x0a, 0xe3, 0x0f, 0xd1, 0x8d,
	0x8c, 0xca, 0xac, 0x36, 0x4d, 0x4b, 0x20, 0x47, 0x20, 0x53, 0xbd, 0x90, 0xa0, 0x16, 0xa2, 0xcc,
	0x7b, 0x17, 0x6c, 0xcd, 0x75, 0x0f, 0x48, 0x5c, 0xfe, 0xe1, 0x2a, 0x3d, 0xfc, 0x23, 0xb0, 0x97,
	0x31, 0xe6, 0x73, 0x81, 0xbf, 0x40, 0x61, 0x56, 0x4b, 0x09, 0x5c, 0x9b, 0x7d, 0xed, 0x65, 0x74,
	0x92, 0xf7, 0x1e, 0x3f, 0x1b, 0x6c, 0xfd, 0xf2, 0x6c, 0xf0, 0xba, 0xbb, 0x79, 0x95, 0x1f, 0x45,
	0x54, 0xc4, 0x8c, 0xe8, 0x45, 0x34, 0xe6, 0xfa, 0xa7, 0xef, 0xde, 0x45, 0xde, 0x12, 0x63, 0xae,
	0xbf, 0xf9, 0xfd, 0xdb, 0x9b, 0xc1, 0x04, 0x79, 0x92, 0x51, 0xcd, 0xf0, 0x97, 0xa8, 0x5b, 0x49,
	0x68, 0xa8, 0xa8, 0x95, 0xe5, 0x6c, 0x6d, 0xc8, 0x19, 0xae, 0x58, 0x0c, 0xe9, 0x5d, 0x14, 0x96,
	0x44, 0x69, 0xaf, 0xa7, 0x95, 0x31, 0x3c, 0xd8, 0x8d, 0x9c, 0xed, 0xa2, 0x95, 0xed, 0xa2, 0x87,
	0x2b, 0xdb, 0x25, 0xaf, 0x99, 0xfd, 0x1e, 0xfd, 0x3a, 0x08, 0x26, 0xc8, 0x14, 0x3a, 0xa9, 0x87,
	0x4f, 0x5b, 0x08, 0xdf, 0xf9, 0xab, 0x2c, 0x92, 0x56, 0xf8, 0x2d, 0x84, 0xb2, 0x05, 0xe1, 0x05,
	0xa4, 0xb3, 0x4a, 0x79, 0x47, 0x76, 0x5c, 0x24, 0xa9, 0x14, 0xbe, 0x85, 0xb0, 0x04, 0x26, 0x34,
	0xa4, 0xd6, 0x30, 0x54, 0xf0, 0x94, 0x3a, 0x5f, 0x6e, 0x4f, 0x76, 0x5c, 0xe6, 0x81, 0x4f, 0x8c,
	0x73, 0xfc, 0x09, 0xea, 0x6a, 0x49, 0x8b, 0x02, 0x24, 0xe4, 0x29, 0xd1, 0xff, 0xea, 0xac, 0xe1,
	0xba, 0x72, 0xa4, 0x5f, 0x10, 0x72, 0xfb, 0x55, 0x08, 0x39, 0x45, 0x97, 0x89, 0xd6, 0xc0, 0x2a,
	0x6d, 0x4e, 0x57, 0x33, 0x6b, 0x96, 0x4d, 0x58, 0xbb, 0x6b, 0x9a, 0x51, 0xcd, 0x86, 0x3f, 0x04,
	0x76, 0x24, 0x9d, 0xcc, 0x78, 0x8c, 0x2e, 0x71, 0x58, 0xfe, 0x27, 0x47, 0x5d, 0xe4, 0xb0, 0x34,
	0xe7, 0x4d, 0x50, 0x67, 0xfd, 0x96, 0x58, 0xc9, 0x5f, 0x56, 0xca, 0xf3, 0x32, 0xfc, 0x36, 0xea,
	0xce, 0x4a, 0x91, 0x1d, 0xa5, 0x0b, 0xa0, 0xc5, 0x42, 0xfb, 0x21, 0x0c, 0x6d, 0xec, 0x53, 0x1b,
	0x1a, 0x3e, 0x0d, 0x50, 0xf8, 0x40, 0xd2, 0x8c, 0xf2, 0xc2, 0xce, 0xc5, 0x14, 0xa1, 0x13, 0x0a,
	0x65, 0x9e, 0x4a, 0x63, 0x37, 0xd7, 0xc4, 0x07, 0xbe, 0x89, 0x37, 0x5f, 0x6c, 0xe2, 0x1e, 0x14,
	0x24, 0x3b, 0x39, 0x84, 0xec, 0xb9, 0x56, 0x0e, 0x21, 0x73, 0xad, 0x74, 0x2c, 0xd3, 0xc4, 0x08,
	0x93, 0xa0, 0x2e, 0xa9, 0xaa, 0x92, 0x42, 0x6e, 0x9f, 0x18, 0xdf, 0xd0, 0x3f, 0xbe, 0x30, 0xa1,
	0x2f, 0xb2, 0xef, 0xe7, 0x2d, 0x84, 0x61, 0x3e, 0x87, 0x4c, 0xd3, 0x06, 0xd2, 0x39, 0x80, 0x3b,
	0x62, 0xdb, 0x9a, 0x76, 0x67, 0x9d, 0xf9, 0x18, 0xc0, 0xec, 0x38, 0xfc, 0xb1, 0x85, 0x3a, 0xf7,
	0x84, 0x52, 0x77, 0x1b, 0xe0, 0xda, 0x8c, 0x7b, 0x29, 0x94, 0x4a, 0x09, 0x13, 0x35, 0xd7, 0x9b,
	0x8f, 0xbb, 0x21, 0x19, 0x59, 0x8e, 0xff, 0x67, 0xdc, 0x9f, 0x33, 0x50, 0xfb, 0x55, 0x1a, 0x68,
	0x7b, 0x23, 0x03, 0x25, 0x1f, 0x3d, 0x3e, 0xed, 0x07, 0x4f, 0x4e, 0xfb, 0xc1, 0x6f, 0xa7, 0xfd,
	0xe0, 0xd1, 0x59, 0x7f, 0xeb, 0xc9, 0x59, 0x7f, 0xeb, 0xe7, 0xb3, 0xfe, 0xd6, 0x57, 0xef, 0xf8,
	0x3b, 0x73, 0x17, 0x78, 0x7c, 0xf2, 0x75, 0xdc, 0xdc, 0x8e, 0xf5, 0x49, 0x05, 0xea, 0xfc, 0x1b,
	0x3c, 0xbb, 0x68, 0xf7, 0xb9, 0xfd, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x25, 0x22, 0x7e, 0x5a,
	0xa4, 0x07, 0x00, 0x00,
}

func (m *AUMBand) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AUMBand) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AUMBand) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpperBound != 0 {
		i = encodeVarintNav(dAtA, i, uint64(m.UpperBound))
		i--
		dAtA[i] = 0x10
	}
	if m.LowerBound != 0 {
		i = encodeVarintNav(dAtA, i, uint64(m.LowerBound))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AUMConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AUMConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AUMConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CircuitBreakerThreshold != 0 {
		i = encodeVarintNav(dAtA, i, uint64(m.CircuitBreakerThreshold))
		i--
		dAtA[i] = 0x28
	}
	if m.MaxAumDeviation != 0 {
		i = encodeVarintNav(dAtA, i, uint64(m.MaxAumDeviation))
		i--
		dAtA[i] = 0x20
	}
	if m.MinAumUpdateInterval != 0 {
		i = encodeVarintNav(dAtA, i, uint64(m.MinAumUpdateInterval))
		i--
		dAtA[i] = 0x18
	}
	if len(m.WithdrawalBands) > 0 {
		for iNdEx := len(m.WithdrawalBands) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WithdrawalBands[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintNav(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.DepositBands) > 0 {
		for iNdEx := len(m.DepositBands) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DepositBands[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintNav(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *AUMInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AUMInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AUMInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.LastUpdate, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.LastUpdate):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintNav(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x1a
	{
		size := m.PreviousAum.Size()
		i -= size
		if _, err := m.PreviousAum.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintNav(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.CurrentAum.Size()
		i -= size
		if _, err := m.CurrentAum.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintNav(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *CircuitBreakerTrip) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CircuitBreakerTrip) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CircuitBreakerTrip) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.AttemptedAum.Size()
		i -= size
		if _, err := m.AttemptedAum.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintNav(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.PreviousAum.Size()
		i -= size
		if _, err := m.PreviousAum.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintNav(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.TriggeredAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.TriggeredAt):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintNav(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x1a
	if m.RemotePositionId != 0 {
		i = encodeVarintNav(dAtA, i, uint64(m.RemotePositionId))
		i--
		dAtA[i] = 0x10
	}
	if m.ChangeBps != 0 {
		i = encodeVarintNav(dAtA, i, uint64(m.ChangeBps))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AUMUpdate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AUMUpdate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AUMUpdate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockHeight != 0 {
		i = encodeVarintNav(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x18
	}
	n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.Timestamp, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Timestamp):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintNav(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x12
	{
		size := m.NewAum.Size()
		i -= size
		if _, err := m.NewAum.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintNav(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PricingInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PricingInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PricingInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EffectiveFeeRate != 0 {
		i = encodeVarintNav(dAtA, i, uint64(m.EffectiveFeeRate))
		i--
		dAtA[i] = 0x18
	}
	if m.AppliedBand != nil {
		{
			size, err := m.AppliedBand.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintNav(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	{
		size := m.YieldRate.Size()
		i -= size
		if _, err := m.YieldRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintNav(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *LossEvent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LossEvent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LossEvent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n5, err5 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.Timestamp, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Timestamp):])
	if err5 != nil {
		return 0, err5
	}
	i -= n5
	i = encodeVarintNav(dAtA, i, uint64(n5))
	i--
	dAtA[i] = 0x22
	{
		size := m.NewAum.Size()
		i -= size
		if _, err := m.NewAum.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintNav(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.PreviousAum.Size()
		i -= size
		if _, err := m.PreviousAum.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintNav(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.LossAmount.Size()
		i -= size
		if _, err := m.LossAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintNav(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintNav(dAtA []byte, offset int, v uint64) int {
	offset -= sovNav(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AUMBand) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LowerBound != 0 {
		n += 1 + sovNav(uint64(m.LowerBound))
	}
	if m.UpperBound != 0 {
		n += 1 + sovNav(uint64(m.UpperBound))
	}
	return n
}

func (m *AUMConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.DepositBands) > 0 {
		for _, e := range m.DepositBands {
			l = e.Size()
			n += 1 + l + sovNav(uint64(l))
		}
	}
	if len(m.WithdrawalBands) > 0 {
		for _, e := range m.WithdrawalBands {
			l = e.Size()
			n += 1 + l + sovNav(uint64(l))
		}
	}
	if m.MinAumUpdateInterval != 0 {
		n += 1 + sovNav(uint64(m.MinAumUpdateInterval))
	}
	if m.MaxAumDeviation != 0 {
		n += 1 + sovNav(uint64(m.MaxAumDeviation))
	}
	if m.CircuitBreakerThreshold != 0 {
		n += 1 + sovNav(uint64(m.CircuitBreakerThreshold))
	}
	return n
}

func (m *AUMInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CurrentAum.Size()
	n += 1 + l + sovNav(uint64(l))
	l = m.PreviousAum.Size()
	n += 1 + l + sovNav(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.LastUpdate)
	n += 1 + l + sovNav(uint64(l))
	return n
}

func (m *CircuitBreakerTrip) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChangeBps != 0 {
		n += 1 + sovNav(uint64(m.ChangeBps))
	}
	if m.RemotePositionId != 0 {
		n += 1 + sovNav(uint64(m.RemotePositionId))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.TriggeredAt)
	n += 1 + l + sovNav(uint64(l))
	l = m.PreviousAum.Size()
	n += 1 + l + sovNav(uint64(l))
	l = m.AttemptedAum.Size()
	n += 1 + l + sovNav(uint64(l))
	return n
}

func (m *AUMUpdate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.NewAum.Size()
	n += 1 + l + sovNav(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Timestamp)
	n += 1 + l + sovNav(uint64(l))
	if m.BlockHeight != 0 {
		n += 1 + sovNav(uint64(m.BlockHeight))
	}
	return n
}

func (m *PricingInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.YieldRate.Size()
	n += 1 + l + sovNav(uint64(l))
	if m.AppliedBand != nil {
		l = m.AppliedBand.Size()
		n += 1 + l + sovNav(uint64(l))
	}
	if m.EffectiveFeeRate != 0 {
		n += 1 + sovNav(uint64(m.EffectiveFeeRate))
	}
	return n
}

func (m *LossEvent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.LossAmount.Size()
	n += 1 + l + sovNav(uint64(l))
	l = m.PreviousAum.Size()
	n += 1 + l + sovNav(uint64(l))
	l = m.NewAum.Size()
	n += 1 + l + sovNav(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Timestamp)
	n += 1 + l + sovNav(uint64(l))
	return n
}

func sovNav(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozNav(x uint64) (n int) {
	return sovNav(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AUMBand) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNav
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AUMBand: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AUMBand: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LowerBound", wireType)
			}
			m.LowerBound = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LowerBound |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpperBound", wireType)
			}
			m.UpperBound = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpperBound |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipNav(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNav
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AUMConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNav
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AUMConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AUMConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositBands", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNav
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNav
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositBands = append(m.DepositBands, &AUMBand{})
			if err := m.DepositBands[len(m.DepositBands)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalBands", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNav
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNav
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WithdrawalBands = append(m.WithdrawalBands, &AUMBand{})
			if err := m.WithdrawalBands[len(m.WithdrawalBands)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinAumUpdateInterval", wireType)
			}
			m.MinAumUpdateInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinAumUpdateInterval |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAumDeviation", wireType)
			}
			m.MaxAumDeviation = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxAumDeviation |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CircuitBreakerThreshold", wireType)
			}
			m.CircuitBreakerThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CircuitBreakerThreshold |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipNav(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNav
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AUMInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNav
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AUMInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AUMInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentAum", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNav
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNav
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CurrentAum.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousAum", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNav
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNav
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PreviousAum.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUpdate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNav
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNav
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.LastUpdate, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNav(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNav
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CircuitBreakerTrip) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNav
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CircuitBreakerTrip: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CircuitBreakerTrip: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChangeBps", wireType)
			}
			m.ChangeBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChangeBps |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemotePositionId", wireType)
			}
			m.RemotePositionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RemotePositionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TriggeredAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNav
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNav
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.TriggeredAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousAum", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNav
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNav
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PreviousAum.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttemptedAum", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNav
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNav
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AttemptedAum.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNav(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNav
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AUMUpdate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNav
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AUMUpdate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AUMUpdate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewAum", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNav
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNav
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NewAum.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNav
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNav
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.Timestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipNav(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNav
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PricingInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNav
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PricingInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PricingInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field YieldRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNav
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNav
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.YieldRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppliedBand", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNav
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNav
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AppliedBand == nil {
				m.AppliedBand = &AUMBand{}
			}
			if err := m.AppliedBand.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EffectiveFeeRate", wireType)
			}
			m.EffectiveFeeRate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EffectiveFeeRate |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipNav(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNav
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LossEvent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNav
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LossEvent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LossEvent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LossAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNav
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNav
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LossAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousAum", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNav
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNav
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PreviousAum.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewAum", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNav
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNav
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NewAum.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNav
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNav
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNav
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.Timestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNav(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNav
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNav(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNav
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNav
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNav
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNav
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupNav
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthNav
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthNav        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNav          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupNav = fmt.Errorf("proto: unexpected end of group")
)
